### ISSUE TITLE
Implementing psr-3 logger interface?

### ISSUE THREAD

**Issue by erickhun** [bufferapp/php-bufflog#5]
Great discussion we had with @esclapes

**Should we satisfy the [psr-3](https://www.php-fig.org/psr/psr-3/) standard?**

One of the goal of the Bufflog project is to make logging for developer super easy by providing them a super simple library to use.  I've come up with a one liner `Buffer\Bufflog::debug("bla");` , but if the library can satisfy current industry standard practise it'd be even better! 

I'm just worrying if we satisfy the psr-3 standard, would it make  Bufflog a bit less friendlier to use?  I'll need to double check that, if my worries aren't correct, I think we will just go ahead with psr-3

 Feel free to drop any thoughts if any @esclapes @colinscape :)

**Comment by colinscape** [comment]
Interesting! It does look quite straightforward to implement, and what we've got already here is pretty close to a valid implementation. I'd say go for it - we can skip the interpolation part for now maybe since that might be a distraction, and it might be an interesting exercise. As well as that, using 'standard' terminology feels like a good thing to do for the benefit of future engineers coming to Buffer.
